# Generated by Django 3.0.1 on 2020-01-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_owners', models.PositiveIntegerField()),
                ('total_sitters', models.PositiveIntegerField()),
                ('total_providers', models.PositiveIntegerField()),
                ('total_pets', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
