# Generated by Django 3.0.3 on 2020-02-16 14:40

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayFastOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('m_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pf_payment_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('custom_str1', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_str2', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_str3', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_str4', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_str5', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_int1', models.IntegerField(blank=True, null=True)),
                ('custom_int2', models.IntegerField(blank=True, null=True)),
                ('custom_int3', models.IntegerField(blank=True, null=True)),
                ('custom_int4', models.IntegerField(blank=True, null=True)),
                ('custom_int5', models.IntegerField(blank=True, null=True)),
                ('name_first', models.CharField(blank=True, max_length=100, null=True)),
                ('name_last', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_id', models.CharField(max_length=15)),
                ('merchant_key', models.CharField(max_length=40)),
                ('sitter_merchant_id', models.CharField(max_length=15)),
                ('sitter_percantage', models.FloatField(default=0.2)),
                ('setup', models.CharField(max_length=200)),
                ('signature', models.CharField(blank=True, max_length=32, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PayFast order',
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_slot', models.PositiveIntegerField()),
                ('notified_sitter', models.BooleanField(default=False)),
                ('sitter_answer', models.BooleanField(default=False)),
                ('notified_owner_of_sitter_response', models.BooleanField(default=False)),
                ('sitter_confirmed', models.BooleanField(default=False)),
                ('owner_payed', models.BooleanField(default=False)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('price_in_cents', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('number_of_pets', models.PositiveIntegerField(default=1)),
                ('reason_for_not_being_able', models.CharField(default='', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=500)),
                ('province', models.CharField(max_length=500)),
                ('street_name', models.CharField(default='', max_length=500)),
                ('area_code', models.PositiveIntegerField()),
                ('street_number', models.CharField(default='', max_length=500)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', imagekit.models.fields.ProcessedImageField(upload_to=core.models.image_directory_path_service_photos)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.CharField(max_length=10000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='sitterservices',
            old_name='listing_name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='sitterservices',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='sitterservices',
            name='score',
        ),
        migrations.AddField(
            model_name='miisitter',
            name='id_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miisitter',
            name='merchant_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='miisitter',
            name='number_of_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='miisitter',
            name='review_score',
            field=models.FloatField(default=6.0),
        ),
        migrations.AddField(
            model_name='miisitter',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='allowed_to_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='birds_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='cats_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='dogs_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='maximum_number_of_pets',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='number_of_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='other_pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='reptiles_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='review_score',
            field=models.FloatField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_end_friday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_end_monday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_end_saturday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_end_sunday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_end_thursday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_end_tuesday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_end_wednesday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_start_friday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_start_monday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_start_saturday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_start_sunday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_start_thursday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_start_tuesday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitterservices',
            name='time_start_wednesday',
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_tcs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pets',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to=core.models.image_directory_path_pet),
        ),
        migrations.AlterField(
            model_name='sitterservices',
            name='price',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='sitterservices',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to=core.models.image_directory_path_service),
        ),
        migrations.AlterField(
            model_name='sitterservices',
            name='type',
            field=models.CharField(choices=[('WALK', 'Walker'), ('BOARD', 'Boarding'), ('SIT', 'House Sitting'), ('DAYCARE', 'Daycare')], default='DAYCARE', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to=core.models.image_directory_path),
        ),
        migrations.DeleteModel(
            name='SitterBooking',
        ),
        migrations.AddField(
            model_name='servicereviews',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicereviews',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SitterServices'),
        ),
        migrations.AddField(
            model_name='servicephotos',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SitterServices'),
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SitterServices'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SitterServices'),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServiceBooking'),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='user_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
