# Generated by Django 3.0.3 on 2020-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200216_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miisitter',
            name='number_of_bookings',
            field=models.CharField(default='', max_length=13),
        ),
    ]
