# Generated by Django 3.0.3 on 2020-02-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200216_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miisitter',
            name='id_number',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='miisitter',
            name='number_of_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
