# Generated by Django 3.0.3 on 2020-02-19 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200216_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterservices',
            name='review_score',
            field=models.FloatField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
