# Generated by Django 3.0.3 on 2020-02-19 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200219_0333'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='servicelocation',
            order_with_respect_to='created_at',
        ),
    ]
