# Generated by Django 3.0.3 on 2020-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200219_0349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payfastorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='custom_int1',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='custom_int2',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='custom_int3',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='custom_int4',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='custom_int5',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='custom_str1',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='custom_str2',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='custom_str3',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='custom_str4',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='custom_str5',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='request_ip',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='sitter_percantage',
        ),
        migrations.RemoveField(
            model_name='payfastorder',
            name='user_pay',
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='amount_fee',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='amount_gross',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='amount_net',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='cancel_url',
            field=models.CharField(default='http://www.miipets.com/payments/cancel-payment', max_length=200),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='confirmation_address',
            field=models.CharField(default='info@miipets.com', max_length=100),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='email_confirmation',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='notified_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='notified_sitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='notify_url',
            field=models.CharField(default='http://www.miipets.com/payments/notify-payment', max_length=200),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='payfast_url',
            field=models.CharField(default='https://payfast.co.za/eng/process', max_length=100),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='return_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='signature_from_payfast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='trusted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payfastorder',
            name='went_to_payfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='amount',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='email_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='item_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='item_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='m_payment_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='merchant_id',
            field=models.CharField(default='14938518', max_length=10),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='merchant_key',
            field=models.CharField(default='w0rseik5fm412', max_length=10),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='name_first',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='name_last',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='payment_status',
            field=models.CharField(default='Not completed', max_length=200),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='pf_payment_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='signature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='sitter_merchant_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
