# Generated by Django 3.0.3 on 2020-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200220_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payfastorder',
            name='merchant_id',
            field=models.CharField(default='14938518', max_length=20),
        ),
        migrations.AlterField(
            model_name='payfastorder',
            name='merchant_key',
            field=models.CharField(default='w0rseik5fm412', max_length=50),
        ),
    ]
