# Generated by Django 3.0.3 on 2020-02-25 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200220_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='price',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='price_in_cents',
            field=models.PositiveIntegerField(default=5000, validators=[django.core.validators.MinValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='sitterservices',
            name='price',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
