# Generated by Django 3.0.1 on 2020-01-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miisitters', '0001_initial'),
        ('miiowners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitterBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miisitters.SitterServices')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miiowners.MiiOwner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
